service:
  name: serverless-todos-rest-api
frameworkVersion: '2'
custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
    target: node14
    define: {}
    platform: node
plugins:
  - serverless-esbuild
provider:
  stage: dev
  region: us-east-1
  name: aws
  runtime: nodejs14.x
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
  lambdaHashingVersion: '20201221'
  versionFunctions: true
functions:
  getCityInfo:
    handler: src/functions/getCityInfo/handler.main
    events:
      - http:
          method: get
          path: getCityInfo/{city}
          cors: true
    name: serverless-todos-rest-api-dev-getCityInfo
